# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krun < Formula
  desc "KRun"
  homepage "https://github.com/artomal/krun"
  version "v0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/artomal/krun/releases/download/v0.0.1/krun_v0.0.1_Darwin_x86_64.tar.gz"
    sha256 "638a21c49bd6f0a680311e4229807f7937dae9e2ed04a57311c1e6f01d74b08e"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/artomal/krun/releases/download/v0.0.1/krun_v0.0.1_Darwin_arm64.tar.gz"
    sha256 "72c1e18f19abd618ff99a6cf16ef5eabd2b2b5066b878a06fece3de6f36d9822"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/artomal/krun/releases/download/v0.0.1/krun_v0.0.1_Linux_x86_64.tar.gz"
    sha256 "cb2ba84056cc6b660d74a20786f62b0461c2a9defdfa8f6598171ad7f751c770"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/artomal/krun/releases/download/v0.0.1/krun_v0.0.1_Linux_arm64.tar.gz"
    sha256 "e87857acab6e9a37b9ae96b140217f9c62977851ace5ff5657ff8b453163fad5"
  end

  def install
    bin.install "krun"
  end
end
